Repository Sparta-bootcamp-master-1team/KioskApp, pull requests merged in 2025-04, with the labels that each got.

#2 feat/init project
  .gitignore
  KioskApp/KioskApp.xcodeproj/project.pbxproj
  KioskApp/KioskApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  KioskApp/KioskApp/AppDelegate.swift
  KioskApp/KioskApp/Assets.xcassets/AccentColor.colorset/Contents.json
  KioskApp/KioskApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  KioskApp/KioskApp/Assets.xcassets/Contents.json
  KioskApp/KioskApp/Base.lproj/LaunchScreen.storyboard
  KioskApp/KioskApp/Info.plist
  KioskApp/KioskApp/SceneDelegate.swift
  KioskApp/KioskApp/ViewController.swift
Labels: ✨Feature

#1 feat: init gitignore
  .gitignore
  KioskApp/KioskApp.xcodeproj/project.pbxproj
  KioskApp/KioskApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  KioskApp/KioskApp/AppDelegate.swift
  KioskApp/KioskApp/Assets.xcassets/AccentColor.colorset/Contents.json
  KioskApp/KioskApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  KioskApp/KioskApp/Assets.xcassets/Contents.json
  KioskApp/KioskApp/Base.lproj/LaunchScreen.storyboard
  KioskApp/KioskApp/Info.plist
  KioskApp/KioskApp/SceneDelegate.swift
  KioskApp/KioskApp/ViewController.swift
Labels: ✨Feature

#11 Feat/#6
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/kioskapp-feature-template.md
  KioskApp/KioskApp/OderList/OrderItemCell.swift
  KioskApp/KioskApp/OderList/OrderListTableView.swift
  KioskApp/KioskApp/OderList/OrderListView.swift
Labels: ✨Feature

#8 Feat/#5
  KioskApp/KioskApp/ProductCell.swift
  KioskApp/KioskApp/ProductGridView.swift
Labels: ✨Feature

#10 Feat/#7
  .gitignore
  KioskApp/KioskApp/Assets.xcassets/megaLogo.imageset/Contents.json
  KioskApp/KioskApp/Assets.xcassets/megaLogo.imageset/megaLogo.png
  KioskApp/KioskApp/CategoryCell.swift
  KioskApp/KioskApp/CoffeeBrandButtonView.swift
  KioskApp/KioskApp/CoffeeCategoryCollectionView.swift
  KioskApp/KioskApp/SceneDelegate.swift
  KioskApp/KioskApp/ViewController.swift
Labels: ✨Feature

#19 Feat/#14
  KioskApp/KioskApp/ViewModel/OrderViewModel.swift
Labels: ✨Feature

#17 Feat/#13
  KioskApp/KioskApp/CategoryCell.swift
  KioskApp/KioskApp/CoffeeBrandButtonView.swift
  KioskApp/KioskApp/CoffeeCategoryCollectionView.swift
  KioskApp/KioskApp/OderList/OrderItemCell.swift
  KioskApp/KioskApp/OderList/OrderListTableView.swift
  KioskApp/KioskApp/OderList/OrderListView.swift
  KioskApp/KioskApp/ProductCell.swift
  KioskApp/KioskApp/ProductGridView.swift
  KioskApp/KioskApp/ViewController.swift
Labels: ✨Feature

#32 Feat/#31
  KioskApp/KioskApp/Model/Model.swift
  KioskApp/KioskApp/ViewController/ViewController.swift
  KioskApp/KioskApp/ViewModel/OrderViewModel.swift
Labels: 🐛BugFix, ✨Feature

#33 Feat/#29
  KioskApp/KioskApp/Views/OderList/OrderItemCell.swift
  KioskApp/KioskApp/Views/OderList/OrderListView.swift
Labels: ✨Feature

#34 Feat/#25
  KioskApp/KioskApp/Views/CoffeeBrandCategoryViews/CoffeCategoryView/CategoryCell.swift
  KioskApp/KioskApp/Views/CoffeeBrandCategoryViews/CoffeCategoryView/CoffeeCategoryCollectionView.swift
  KioskApp/KioskApp/Views/CoffeeBrandCategoryViews/CoffeeBrandButtonView.swift
Labels: ✨Feature

#35 Feat/#27
  KioskApp/KioskApp/ViewController/ViewController.swift
  KioskApp/KioskApp/ViewModel/OrderViewModel.swift
  KioskApp/KioskApp/Views/SpinnerView.swift
Labels: ✨Feature

#38 Feat/#37
  KioskApp/KioskApp/Assets.xcassets/BrandLogos/MegaLogo.imageset/MegaLogo.png
  KioskApp/KioskApp/Assets.xcassets/LoadingViewImage.imageset/Contents.json
  KioskApp/KioskApp/Assets.xcassets/LoadingViewImage.imageset/LoadingViewImage.jpg
  KioskApp/KioskApp/Assets.xcassets/megaLogo.imageset/megaLogo.png
  KioskApp/KioskApp/Views/SpinnerView.swift
Labels: 👍Enhance, ✨Feature

#50 Feat/#48
  KioskApp/KioskApp/ViewModel/OrderViewModel.swift
  KioskApp/KioskApp/Views/OderList/OrderItemCell.swift
  KioskApp/KioskApp/Views/OderList/OrderListTableView.swift
  KioskApp/KioskApp/Views/OderList/OrderListView.swift
Labels: 👍Enhance, ✨Feature

#51 dose: README 생성 및 작성
  README.md
Labels: 📄Docs
